import os
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.getenv("API_KEY")
SECRET_KEY = os.getenv("SECRET_KEY")
ALPACA_PAPER = os.getenv("ALPACA_PAPER", "true").lower() == "true"

UNDERLYINGS = ["SPY", "QQQ", "AAPL", "MSFT", "NVDA"]

DOLLARS_PER_TRADE = 100
MAX_POSITIONS = 2

MA_SHORT = 50
MA_LONG = 200
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9

MIN_DTE = 30
MAX_DTE = 60

MIN_OPEN_INTEREST = 500
MIN_OPTION_VOLUME = 100
MAX_BID_ASK_SPREAD_PCT = 0.05
TARGET_DELTA = 0.60
DELTA_TOLERANCE = 0.10
EARNINGS_SKIP_DAYS = 1  # skip if earnings are today or tomorrow
OPTION_DATA_FEED = os.getenv("OPTION_DATA_FEED", "indicative")

ENABLE_MARKET_REGIME_FILTER = True
MARKET_REGIME_SYMBOL = "SPY"
MARKET_REGIME_SHORT_MA = 50
MARKET_REGIME_LONG_MA = 200

UNDERLYING_STOP_LOSS_PCT = 0.03
UNDERLYING_TAKE_PROFIT_PCT = 0.08

OPTION_PREMIUM_ESTIMATE_PERCENT = 0.03
OPTION_LEVERAGE_MULTIPLIER = 5
OPTION_STOP_LOSS_PERCENT = 0.50
OPTION_TAKE_PROFIT_PERCENT = 1.00
MAX_HOLDING_DAYS = 20

OPTION_TYPE = "call"  # start with calls only
CONTRACT_QTY = 1

SCAN_INTERVAL_SECONDS = 300

LOG_FILE = "logs/options_bot.log"
ANALYTICS_FILE = "logs/trade_analytics.csv"
